// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client.
// Prefer SUPABASE_SERVICE_ROLE_KEY for trusted admin operations when available.
// Falls back to the publishable key so the app can run on Cloudflare Free without a service-role secret.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseAdminClient() {
  const env = import.meta.env;
  const supabaseUrl = env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!supabaseUrl || !supabaseKey) {
    const missing = [
      !supabaseUrl ? "VITE_SUPABASE_URL" : null,
      !supabaseKey ? "VITE_SUPABASE_PUBLISHABLE_KEY" : null,
    ].filter(Boolean);
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Configure GitHub Actions secrets.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(supabaseUrl, supabaseKey, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
